### ISSUE TITLE
Commercial Licensing? 

### ISSUE THREAD

**Issue by techdragon** [viewflow/jsonfield-schema#10]
I'm categorically unable to work with the AGPL under some circumstances (Not my choice, I don't work in legal), and so having a commercial license option similar to the viewflow/viewflow library "pro" option would be useful.

**Comment by kmmbvnr** [comment]
Currently it' available as part of commercial licence of viewflow https://raw.githubusercontent.com/viewflow/viewflow/master/COMM-LICENSE.txt

**Comment by techdragon** [comment]
Oh cool! It might be worth mentioning this in the docs for this repo. Also a possibly of a separate lower cost licence for projects that don't need the rest of viewflow would be a nice to have.

**Comment by kmmbvnr** [comment]
I'm closing the issue, since whole package was moved to became part of Viewflow 

https://github.com/viewflow/viewflow/blob/main/viewflow/jsonstore.py

As for the lower cost, unfortunately it's probably won't happens in the near future, since no more requests on this
