### ISSUE TITLE
JSON field created out of thin air

### ISSUE THREAD

**Issue by Natureshadow** [viewflow/jsonfield-schema#3]
While adding jsonstore to a project, the following problem occurred:

After adding a JSON field to a model to use with jsonstore, Django detected the model change and created the appropriate migration. However, it does not work, because the JSON field is always created on the table, even without a migration doing that. It appears as soon as the initial migration runs, even though it is not defined in the initial migration.

The behaviour would be ok if Django didn't want to create a new migration for the field, even though it is already on the table at the time when makemigrations runs.

Is there any reason for this behaviour? Until now, I failed to find out why the field is created, and also why Django seems to ignore it when creating migrations.

Environment: Python 3.8, Django 3.0, PostgreSQL.

**Comment by kmmbvnr** [comment]
a JSONField is not a part of this project. You should use an appropriate implementation from other project

jsonstore.*Field(...) virtual fields are not went into migrations

**Comment by Natureshadow** [comment]
> a JSONField is not a part of this project. You should use an appropriate implementation from other project
> 
> jsonstore.*Field(...) virtual fields are not when into migrations

This is entirely incorrect. JSONField is an important part of this
project, and must be used as storage for the virtual fields. There is a
JSONField wrapper here that select the correct implementation for the
backend in use.

**Comment by kmmbvnr** [comment]
JSONField wrapper is just an internal API for test purpose.

For real project use appropriate JSONField impl from other projects. jstore virtual fields could works with any jsonfield implementation

**Comment by Natureshadow** [comment]
> JSONField wrapper is just an internal API for test purpose.
> 
> For real project use appropriate JSONField impl from other projects. jstore virtual fields could works with any jsonfield implementation

Please rename it to _JSONField if it is not a public API.

In any case, are you just turning down users and potential contributors,
or are you trying to say "The JSONField wrapper creates the field on the
table when first called, and this is known and intended"? I do not see
any hint on that, but it would actually be helpful to know it even if
your publicly marked API is not public.

Thanks!

**Comment by kmmbvnr** [comment]
Yeah, good point.

But i think it would be soon obsolete since Django would release db agnostic JSONField
