### ISSUE TITLE
AGPL licence warning?

### ISSUE THREAD

**Issue by andybak** [viewflow/jsonfield-schema#4]
Unless I'm mistaken any project that uses this will also be under the AGPL - which is a pretty major fact for anyone using it to be aware of.

I nearly overlooked this as it's fairly unusual in Django world. It would have been very problematic as the rest of my code is MIT licensed.

Considering this is fairly out of the ordinary - would it be a good idea to put a much clearer warning higher up in the readme? Not everyone is a licence lawyer and many people will just think "oh cool. open source"

**Comment by kmmbvnr** [comment]
Yep, the Readme file contains the section regarding the license. If you are using standard CPython distribution under common Linux distributive, you are already have components with APGL+Exceptions that allows linking but prevents selling modified libraries without code distribution.
