### ISSUE TITLE
values_list returns full JSON field instead of just requested values

### ISSUE THREAD

**Issue by Natureshadow** [viewflow/jsonfield-schema#7]
When using the `QuerySet`'s `values_list` method to retrieve only a list containing the values of selected fields, and using jsonstore field, the resulting list gets the whole JSON field represented as a string instead of only the extracted single field.

Can we somehow hook into the API there and make `values_list` work for jsonstore fields?

**Comment by kmmbvnr** [comment]
That's the good question.

Need to be investigated

https://github.com/django/django/blob/6307c3f1a123f5975c73b231e8ac4f115fd72c0d/django/db/models/query.py#L113

https://github.com/django/django/blob/464a4c0c59277056b5d3c1132ac1b4c6085aee08/django/db/models/sql/compiler.py#L1120

https://github.com/django/django/blob/a9a7421ab83361746549d574ca13438ba93c95fe/django/db/models/fields/related.py#L1011

```diff
+    def convert_json_value(self, value, expression, connection):
+        if isinstance(value, str):
+            import json
+            return json.loads(value)[self.name]
+        return value
+
+    def get_db_converters(self, connection):
+        converters = super().get_db_converters(connection)
+        converters += [self.convert_json_value]
+        return converters
+
```

**Comment by kmmbvnr** [comment]
Unfortunately, i can't find a way to improve this.

Lets leave this as a known limitation

**Comment by kmmbvnr** [comment]
Heh, just fixed this. Already available as https://github.com/viewflow/viewflow/blob/main/viewflow/jsonstore.py
