### ISSUE TITLE
Remove mutable defaults from example

### ISSUE THREAD

**Issue by budlight** [viewflow/jsonfield-schema#9]
```
data = JSONField(default={})
```

should be

```
data = JSONField(default=dict)
```

on both 
https://github.com/viewflow/jsonstore/blob/master/README.rst
and 
https://pypi.org/project/django-jsonstore/

**Comment by kmmbvnr** [comment]
Thank you for the notices.

To improve maintenance cost the the package was moved into viewflow v2 - https://github.com/viewflow/viewflow

The issue was fixed.
